name: Checkout Issue Repro

trigger: none

pool:
  vmImage: 'windows-latest'

jobs:
- job: CheckoutTest
  steps:
  - checkout: git://raujaiswal/checkout@refs/heads/main
    fetchTags: false
    fetchFilter: blob:none
    displayName: Checkout Test - Main

  - checkout: self
    fetchTags: false
    displayName: Checkout Test - Self